### ISSUE TITLE
Use a more stable API

### ISSUE THREAD

**Issue by Timecraft** [Timecraft/retro-games#2]
Using retro-gtk-1 is risky, as the API is likely to break ([see this blog post for details](https://blogs.gnome.org/alexm/2020/02/04/games-and-retro-gtk-happenings/)). We should move this back to the version that is in the repositories, which I believe is retro-gtk-0-14 (something like this)

**Comment by Timecraft** [comment]
Moved back to retro-gtk-0.18.1 and it actually made the RetroGtk parts of the app stop working. Now the game will not run, even though a `MainLoop` was created and told to `start ()`. Not sure what's going on here

**Comment by Exalm** [comment]
Works here.

![Screenshot from 2020-02-20 14-07-15](https://user-images.githubusercontent.com/1510457/74918027-66b22a80-53c0-11ea-9313-56a159ee4845.png)

**Comment by Timecraft** [comment]
Can confirm that it is now working, thanks to your fixes in `view.vala`
