### ISSUE TITLE
Custom controls

### ISSUE THREAD

**Issue by Timecraft** [Timecraft/retro-games#4]
With some fun discussion in #1, it has become clear that customized controls should be something that comes much sooner rather than much later

**Comment by Timecraft** [comment]
It looks like this //might// be working? Someone is likely going to prove me wrong on this, so reopen this if you find something

**Comment by alainm23** [comment]
Hey, buddy, I'm interested in this project. If you want some code to capture the user's input buttons, look here: https://github.com/alainm23/planner/blob/master/src/Dialogs/Preferences/Preferences.vala#L535

**Comment by Timecraft** [comment]
I actually (to some extent) [am doing that](https://github.com/Timecraft/retro-games/blob/f394da9df62fb85752bcbe8d4765690e817f5807/src/widgets/control_window.vala#L139), but am using the button press event to record it and then am waiting to hear a button release event before allowing the user to give the app the next button. I’ll try just making that a release event and see if I like that better, though! Thanks so much!

**Comment by Timecraft** [comment]
Yeah, that works pretty well. Thanks for that tip!

**Comment by Timecraft** [comment]
Setting the controls with the keyboard works perfectly fine.
**HOWEVER**
Setting the controls with a controller does NOT work.

**Comment by Timecraft** [comment]
** UPDATE **

I set the controller to port 0 (1) of the "console", and it is working*

* It is doing what it is supposed to: `Retro.JoypadId.START == 315`, and it is firing START when it hears that code. **HOWEVER**, that code corresponds to the right stick button on my gamepad, which is not what we want.

**Comment by Exalm** [comment]
`Retro.KeyJoypadMapping` is for keyboard. For gamepads mappings are handled by libmanette.

This isn't a part of retro-gtk because libmanette is also used without it.

**Comment by Exalm** [comment]
There is a database of default mappings (from SDL), but chances are your controller is not there. There isn't any standard there, so you might need to map it.

Basically, you should create a mapping and use `device.save_user_mapping()` (or `device.remove_user_mapping()` to reset it. This is per-device, based on the device GUID. The format are SDL strings, same as what's shipped in the database:

An example of such a string:

```
05000000c82d00002038000000010000,8Bitdo NES30 Pro,platform:Linux,a:b1,b:b0,y:b3,x:b4,start:b11,guide:b2,back:b10,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a5,lefttrigger:b8,righttrigger:b9,
```

**Comment by Timecraft** [comment]
Ah, that makes sense. I was working with it a little bit more, and I see some of the issues. My controller is styled after a GameCube controller, and it looks as though retro-gtk/libmanette looks at it as though it's an XBox controller (A is B, B is A). That fixed a *tiny* amount of it, but the DPad is analog, which isn't entirely helpful

**Comment by Exalm** [comment]
Here's how gnome-games builds the mapping it FTR: https://gitlab.gnome.org/GNOME/gnome-games/-/blob/master/src/gamepad/gamepad-mapping-builder.vala

> looks at it as though it's an XBox controller

It might be actually detected as an xbox controller, a lot of them do that. E.g. my 8bitdo SN30 Pro USB does this, and N30 Pro can switch the mode based on what button you hold when you power it on. In "Windows mode" it's recognized as an xbox controller, in "Android mode" it's recognized properly.

DPad is analog - I had that on another controller (a cheap knockoff of SNES controller from China). There is a way to map those, here's the mapping for that controller:

```
030000001008000001e5000010010000,usb gamepad           ,platform:Linux,a:b2,b:b1,y:b0,x:b3,start:b9,back:b8,leftshoulder:b4,rightshoulder:b6,dpup:-a1,dpleft:-a0,dpdown:+a1,dpright:+a0,
```

Notice the `-a0` and `+a0`. There's also `~a0` which inverts the axis value.

However, is it actually analog or hat? Hats are different, that's the `h0.1` etc.

**Comment by Timecraft** [comment]
Sometimes the string that Manette gets is "Generic X-Box pad", but sometimes it is "HORI CO.,LTD HORIPAD S", which is what it is

**Comment by Timecraft** [comment]
It is hat. It sends a signal when I connect to the device hat signal

**Comment by Exalm** [comment]
Also note that it's impossible to have all controllers working OOTB as much as I'd like to. There are controllers that have the  same GUID but different physical buttons: in addition to that SNES knockoff I have a similar NES one, and it has the same GUID, but A,B buttons correspond to X,B buttons on the SNES one 😠️ and it's impossible to map them both at the same time.

**Comment by Timecraft** [comment]
> Also note that it's impossible to have all controllers working OOTB as much as I'd like to.
This is why I('m trying to) have it set up so that the user can make sure the controls are what they expect them to be

**Comment by Exalm** [comment]
> It is hat. It sends a signal when I connect to the device hat signal

Ok, so then you map it like in the first string I showed.

The fact it detects differently - I'm inclined to say that's the issue of the particular gamepad. :/ We really just read what it sends.

**Comment by Exalm** [comment]
> This is why I('m trying to) have it set up so that the user can make sure the controls are what they expect them to be

Sure. Just saying that you shouldn't be surprised if your controller isn't properly mapped out of the box.

**Comment by Timecraft** [comment]
With the latest commit, I was able to create and store an SDL string to try to make custom controls. 
However, only `START` seems to work, and `B` is doing something weird. Seems like it's acting like ~`SELECT` or `START?`~ after further review, it seems like it might be acting as `A` .
On the DPad: `UP` is acting as `LEFT` and `RIGHT` is acting as `UP`, but neither DPAD `LEFT` or `DOWN` do anything. This is probably something I did wrong.

**Comment by Timecraft** [comment]
For reference, this is the generated SDL string:
`"platform:Linux,a:b2,b:b1,y:b3,x:b0,dpup:h0.2,dpleft:h0.1,leftshoulder:b6,lefttrigger:b4,leftstick:b10,back:b8,rightshoulder:b7,righttrigger:b5,rightstick:b11,start:b9,"`
The GamepadMappingBuilder is wholesale from GNOME-Games, let me know if I should rewrite it or if it is ok to reuse that code. Don't want to infringe on anything.

**Comment by Timecraft** [comment]
Judging by this string: 
```
030000001008000001e5000010010000,usb gamepad           ,platform:Linux,a:b2,b:b1,y:b0,x:b3,start:b9,back:b8,leftshoulder:b4,rightshoulder:b6,dpup:-a1,dpleft:-a0,dpdown:+a1,dpright:+a0,
```
, I’m guessing that the string I am generating is missing some things, mainly the GUID (`030000001008000001e5000010010000`) and the name of the controller (`usb gamepad`)

**Comment by Timecraft** [comment]
I’m going to try modifying [this section](https://github.com/Timecraft/retro-games/blob/8e8005721b808dcedacc7adb2f961e49e805d4e9/src/core/gamepad_mapping_builder.vala#L20) to match with the order I’m assigning the buttons first, just to make sure it’s not that part.

**Comment by Exalm** [comment]
> "platform:Linux,a:b2,b:b1,y:b3,x:b0,dpup:h0.2,dpleft:h0.1,leftshoulder:b6,lefttrigger:b4,leftstick:b10,back:b8,rightshoulder:b7,righttrigger:b5,rightstick:b11,start:b9,"

I'm not seeing dpdown and dpright?

**Comment by Timecraft** [comment]
...do tell... huh. I’ll have to look into that, too. While that doesn’t explain the other buttons not doing anything, that might explain DPADs UP and RIGHT being the wrong action. UP and RIGHT are being mapped to dpleft and dpup respectively

**Comment by Timecraft** [comment]
Using the boolean return statement in `GamepadMappingBuilder.set_hat_mapping` returns `false` for DPads DOWN and RIGHT. I assume that is meaning that it is failing that assignment and is not due to the axis being negative or positive?
```
** Message: 12:55:32.975: control_window.vala:286: Mapping BTN_DPAD_UP: true
** Message: 12:55:33.375: control_window.vala:286: Mapping BTN_DPAD_DOWN: false
** Message: 12:55:33.715: control_window.vala:286: Mapping BTN_DPAD_LEFT: true
** Message: 12:55:34.075: control_window.vala:286: Mapping BTN_DPAD_RIGHT: false
```

**Comment by Exalm** [comment]
What are the values `event.get_hat()` returns? I mean, you're doing more or less the same thing as Games here.

https://gitlab.gnome.org/GNOME/gnome-games/-/blob/master/src/ui/gamepad-mapper.vala - the class that does the mapping for reference.

**Comment by Exalm** [comment]
> I should rewrite it or if it is ok to reuse that code

Nah, feel free to reuse anything from there. It's GPLv3+, so it's fine.

**Comment by Timecraft** [comment]
```
** (com.github.timecraft.retro:22755): CRITICAL **: 13:03:53.499: control_window.vala:286: axis: 17, value: 0, BTN_DPAD_UP

** (com.github.timecraft.retro:22755): CRITICAL **: 13:03:53.899: control_window.vala:286: axis: 17, value: 0, BTN_DPAD_DOWN

** (com.github.timecraft.retro:22755): CRITICAL **: 13:03:54.183: control_window.vala:286: axis: 16, value: 0, BTN_DPAD_LEFT

** (com.github.timecraft.retro:22755): CRITICAL **: 13:03:54.499: control_window.vala:286: axis: 16, value: 0, BTN_DPAD_RIGHT
```

Made them critical so that they could be easily seen.

**Comment by Exalm** [comment]
Well, value = 0 is indeed incorrect. You can see that in my binding they are 1,2,4,8. In Games it's skipped when value == 0.

**Comment by Exalm** [comment]
Aah. I bet it becomes 0 when you release the dpad.

**Comment by Timecraft** [comment]
Ah. That'll do it, because I'm waiting to record that until after I release it so that it felt more like setting the other buttons, which I do after release. I'll move that to be on press.

**Comment by Timecraft** [comment]
Generated string after this fix:
```
platform:Linux,a:b2,b:b1,y:b3,x:b0,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftshoulder:b6,lefttrigger:b4,leftstick:b10,back:b8,rightshoulder:b7,righttrigger:b5,rightstick:b11,start:b9,
```

Yep, that did it. I see a dpad up, down, left, and right.

**Comment by Exalm** [comment]
Yep, looks like it. Now, as for buttons, make sure you didn't swap A/B and X/Y accidentally.

**Comment by Timecraft** [comment]
Oh wonderful, it almost completely works how I'd expect it to :smile:

**Comment by Timecraft** [comment]
Nope, A and B look like they're working fine with one caveat: A and B are swapped. I suppose that's X-Box vs GameCube there.

**Comment by Exalm** [comment]
Yes, that's what I meant. I mean, did you actually press them in correct order etc? Can you push the code so I can try it?

**Comment by Timecraft** [comment]
I'm pressing A when the indicator lights up for the primary button, which is A on gamecube style controllers.

Code has been pushed up for your perusal, tests, and critique

**Comment by Exalm** [comment]
```
../src/widgets/control_window.vala:271.49-271.82: error: Argument 2: Cannot convert from `uint16' to `string'
            debug ("device hardware index: %s", device_event.get_hardware_index ());
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by Timecraft** [comment]
Whoops, forgot `.to_string ()` haha

**Comment by Timecraft** [comment]
Try it now :sweat_smile:

**Comment by Timecraft** [comment]
Based on one of the warnings, I think I might have accidentally deleted the `set_hat_mapping` usage?

**Comment by Timecraft** [comment]
Oh yeah, I definitely did something bad. Version control to the rescue!

**Comment by Exalm** [comment]
You did remove it, yes.

```
gamepad_mapper.set_hat_mapping ((uint8) device_event.get_hardware_index (), (int32) val, STANDARD_GAMEPAD_INPUTS [current_button ++]);
```
BTW, no need for `(int32)`.

As for the buttons, there's no such thing as "primary button" in either libmanette or libretro, it's simply A/B/X/Y.

And you should add a way to skip a button. On my controller L2 and R2 are axes and so I can't set it up properly. Of course this won't be an issue once you handle them, but I also have that SNES-like controller without those buttons at all :p

**Comment by Timecraft** [comment]
[Fixed] (https://github.com/Timecraft/retro-games/commit/41bbc185491fae646ab87c97e6c8b2139ac93b5a)

**Comment by Timecraft** [comment]
> And you should add a way to skip a button

That's my next goal, using escape on the keyboard to set the key to nothing

**Comment by Exalm** [comment]
Well, if you also write that, I guess it works.

**Comment by Timecraft** [comment]
> As for the buttons, there's no such thing as "primary button" in either libmanette or libretro, it's simply A/B/X/Y.

I use the term "primary button" to mean the button that is typically used for interaction in games. For most (if not all) Nintendo games, this is A. Not sure about X-Box, but I think it's A on there too? PS4 I believe it is usually X or O.

**Comment by Exalm** [comment]
There's no "usually", e.g. on PlayStation it differs between regions even.

**Comment by Timecraft** [comment]
> On my controller L2 and R2 are axes and so I can't set it up properly

Yeah, I noticed that in the few seconds before my controller is recognized (when it is labelled as a generic X-Box pad) it fires an `absolute_axis_event`. I'll add that in shortly too

**Comment by Timecraft** [comment]
> There's no "usually", e.g. on PlayStation it differs between regions even

...DANGIT... :laughing:

**Comment by Exalm** [comment]
I'd suggest to stick to A/B/X/Y really :) There's no need to invent your own terminology as it might only lead to more confusion really.

**Comment by Exalm** [comment]
And you also need a way to map sticks after you add axes support. They are needed e.g. for PlayStation games.

**Comment by Exalm** [comment]
And BTN_MODE is home button.

**Comment by Timecraft** [comment]
> And BTN_MODE is home button.

That's the one I was mostly confused about.

> I see you have "X? Y?" comments. X means horizontal axis, Y - vertical axis.

The "?" are mostly because of the sticks. I'm assuming that the ones that are not prepended with an R are for the left (GameCube control stick) and the ones that are prepended R are for the right (GameCube C-stick).

**Comment by Exalm** [comment]
Yes.

**Comment by Timecraft** [comment]
As for adding axis controls, I have noticed that when pushing the stick up, it fires that signal at least 4 times depending on the speed you push it out

**Comment by Exalm** [comment]
Of course, because it's analog :) In Games we check whether it's larger than 0.8 (or smaller than -0.8), but it's indeed not ideal right now and it's easy to accidentally map 2.

**Comment by Exalm** [comment]
I see, on the svg used in Games we have a,b,x,y like on Xbox controller.

**Comment by Timecraft** [comment]
> In Games we check whether it's larger than 0.8 (or smaller than -0.8), but it's indeed not ideal right now and it's easy to accidentally map 2.

By checking `value`, I'm guessing?

**Comment by Exalm** [comment]
also
```
{ { EventCode.EV_KEY, EventCode.BTN_Y }, "x" },
{ { EventCode.EV_KEY, EventCode.BTN_X }, "y" },
```

I don't remember exactly why, but there was some weirdness with these.

> By checking value, I'm guessing?

Yes. Also don't forget to special-case dpad so that those controllers that expose dpad as 2 axes work. Check out that file I linked earlier really. :)

**Comment by Timecraft** [comment]
> I see, on the svg used in Games we have a,b,x,y like on Xbox controller.

I'm questioning myself as to how I should do this. I'm thinking on those buttons, just don't show the highlights to keep confusion down and showing a label with the button's name on it.

Thinking about that, even showing the name would give me the wrong values, as A on an X-Box controller is not the same as A on a GameCube controller, and there are not buttons for those on the PS4 controller

**Comment by Timecraft** [comment]
> Check out that file I linked earlier really.

Yeah, I have it up. I'm hesitant to copy too much code from Games, even if it is GPLv3. Makes my app feel less like my work and more like a skin over Games, at least to me.

**Comment by Exalm** [comment]
> I'm questioning myself as to how I should do this. I'm thinking on those buttons, just don't show the highlights to keep confusion down and showing a label with the button's name on it.

Nah, I think showing the position is fine. There's just a bug right now.

**Comment by Timecraft** [comment]
> Thinking about that, even showing the name would give me the wrong values, as A on an X-Box controller is not the same as A on a GameCube controller

But it'll give the same value, derr

**Comment by Exalm** [comment]
I mean, "A" is meaningless on a PlayStation controller, so that's an immediate no-go.

**Comment by Timecraft** [comment]
> Nah, I think showing the position is fine. There's just a bug right now.

I only disagree with this because I think it would lead to confusion. Like, I have a GameCube controller, and the app is showing me to press the button on the far right. But it's also telling me to press the button labelled "B", but B is on the bottom of that diamond. What do I press?!

> I mean, "A" is meaningless on a PlayStation controller, so that's an immediate no-go.
Yeah, that's the problem. If I can figure out what button A on the X-Box translates to on the PlayStation, I can say (for argument sake, we'll say it's triangle) "A or Triangle"

**Comment by Exalm** [comment]
> But it's also telling me to press the button labelled "B"

What? I don't see that in your UI.

**Comment by Timecraft** [comment]
Perhaps you could first ask the user some questions. "Is there a button labelled A?" "Which button is labelled A?"

**Comment by Timecraft** [comment]
> What? I don't see that in your UI.

You're not seeing it because it's not there. Its concepts I'm working on in my head. I'll mock up a quick image of what I mean.

**Comment by Exalm** [comment]
I mean, with xbox controller you _do_ want to map A as B and B to A. Otherwise it's a muscle memory disaster.

**Comment by Exalm** [comment]
So it's really about placement and not labels. Labels will be different with each platform. E.g. on my SNES-like controller on N64 A and B correspond to B and Y and C-buttons are the right stick.

**Comment by Timecraft** [comment]
![controller-button-secondary-with-label svg](https://user-images.githubusercontent.com/28582777/75477120-cdf44f80-5969-11ea-88f9-b0b9feca19b0.png)

**Comment by Exalm** [comment]
That's... smaller than I expected. :p

**Comment by Timecraft** [comment]
> I mean, with xbox controller you do want to map A as B and B to A. Otherwise it's a muscle memory disaster.

True. Perhaps I just need to reverse how they are done in the code

**Comment by Timecraft** [comment]
> That's... smaller than I expected. :p

128x128. The SVG base is scaled up to 512x512 in the app from its starter of 128x128

**Comment by Timecraft** [comment]
I guess if A and B are reversed, X and Y probably are too. I'll reverse both of those

**Comment by Exalm** [comment]
That's not an svg though.

**Comment by Exalm** [comment]
You can use SNES Burn-In Cartridge as an easy reference. :)

**Comment by Exalm** [comment]
And in fact only A and B are reversed right now, not X and Y.

**Comment by Exalm** [comment]
Other than that, I'd recommend to use structs instead of parallel arrays...

**Comment by Timecraft** [comment]
> Other than that, I'd recommend to use structs instead of parallel arrays...

May I ask what for?

**Comment by Exalm** [comment]
IDK, I find that more readable 🤷️

**Comment by Timecraft** [comment]
I mean literally what for. Like, which part of the code?

**Comment by Exalm** [comment]
Ah. The `standard_gamepad_inputs_as_string` etc in ControlWindow.

**Comment by Exalm** [comment]
Oh BTW you don't need to store gamepad controls yourself, it's done by libmanette. See `~/.config/libmanette/gamecontrollerdb`.

**Comment by Timecraft** [comment]
> Oh BTW you don't need to store gamepad controls yourself, it's done by libmanette. See ~/.config/libmanette/gamecontrollerdb.

Oh, I didn't know that. I'll have to look at how to read that file

**Comment by Exalm** [comment]
I mean it's automatic.

**Comment by Timecraft** [comment]
> I mean it's automatic. You set mapping and it's loaded automatically next time.

:open_mouth:

**Comment by Timecraft** [comment]
Ok, that is actually awesome

**Comment by Exalm** [comment]
Ok, so:

From `/usr/include/linux/input-event-codes.h`:
```c
#define BTN_A			BTN_SOUTH
#define BTN_B			BTN_EAST
#define BTN_X			BTN_NORTH
#define BTN_Y			BTN_WEST
```

And from retro-gtk:
```c
 * @RETRO_JOYPAD_ID_B: the bottom action button
 * @RETRO_JOYPAD_ID_Y: the left action button
 * @RETRO_JOYPAD_ID_A: the right action button
 * @RETRO_JOYPAD_ID_X: the top action button
```

You can see that X/Y match, while A/B are swapped. In gnome-games controller svg the a/b/x/y are all like on XBox controller, so the code swaps X/Y to compensate. You need to do the opposite and swap A/B instead.

**Comment by Timecraft** [comment]
Yeah, I swapped A and B and it works perfectly now

**Comment by Exalm** [comment]
And in libmanette it's swapped too to compensate for the `input-event-codes.h` weirdness.

```c
    { EV_KEY, BTN_Y, "x" },
    { EV_KEY, BTN_X, "y" },
```

So as a result `gamepad-mapping-builder.vala` swaps it too. And then to compensate for swapped graphics. And then in gnome-games' `PreferencesSubpageGamepad` X/Y are once again swapped, BUT we also have swapped graphics.

Phew. What a mess.

**Comment by Timecraft** [comment]
> And in libmanette it's swapped too to compensate for the input-event-codes.h weirdness.
> ```
>    { EV_KEY, BTN_Y, "x" },
>    { EV_KEY, BTN_X, "y" },
> ```
>So as a result gamepad-mapping-builder.vala swaps it too. And then to compensate for swapped graphics. And then in gnome-games' PreferencesSubpageGamepad X/Y are once again swapped, BUT we also have swapped graphics.

> Phew. What a mess.

So you have the swapped graphics because the buttons are swapped, and there's a swap.... another swap... I think I got lost less than halfway through :laughing:

**Comment by Exalm** [comment]
Not me, the mapping was done by a GSoC intern and I wasn't even maintainer at the time. :p

https://gitlab.gnome.org/GNOME/gnome-games/-/commit/320e9c11bcc437e5fd0f638c23d05901911ad2ca
https://gitlab.gnome.org/GNOME/gnome-games/-/commit/938a529d2c972e986a2ef6d1876bbe9416849f07

Hopefully this makes it a little clearer. Feel free to sync up the changes into your app. :)

**Comment by Exalm** [comment]
Also, this is a perfect example of what happens when you try to use labels instead of positions. 🙄️

**Comment by Timecraft** [comment]
While I don't have a ROM to test it with, I think I have the full set up done, including the analog stick axes.

**Comment by Timecraft** [comment]
Also changed the icons to reflect their position (north, east, south, west) rather than the label on the button

**Comment by Exalm** [comment]
Right now if you map analog, it's pretty much guarantee you'll map 2 axes instead of 1. Games has this too, but not as prominent because it doesn't allow to set the same axis multiple times.

**Comment by Exalm** [comment]
Other than that, works for me, even that gamepad with dpad-as-axes. 👍️

**Comment by Exalm** [comment]
Oh, and add skipping, it's really needed as not all gamepads have all buttons.

**Comment by Timecraft** [comment]
I'll have to test that later when I can get my hands on a GameCube or N64 ROM. One issue would be that my computer is probably unable to handle N64 or above

**Comment by Timecraft** [comment]
> Oh, and add skipping, it's really needed as not all gamepads have all buttons.

https://github.com/Timecraft/retro-games/blob/c503800dc8ad9225a6bdc3579c9eecdfe2a4cd53/src/widgets/control_window.vala#L196-L206

**Comment by Timecraft** [comment]
It's bound to the Escape key. Maybe I should add a label to make that more obvious

**Comment by Exalm** [comment]
No need to as retro-gtk can't handle OpenGL cores right now :p

It will be able to after https://gitlab.gnome.org/GNOME/retro-gtk/merge_requests/60, but that's 1.0 only because it absolutely requires running in subprocess, which is the reason for most of the API changes there.

You can try PSX though, there are games like Ape Escape. Don't forget to set `pcsx_rearmed_pad1type=dualshock` though if you're using that core, as that game won't start otherwise.

**Comment by Exalm** [comment]
> It's bound to the Escape key. Maybe I should add a label to make that more obvious

Yes, you should. That's completely undiscoverable: who would even think to press a keyboard key when you have a gamepad in your hands? ;) I'd suggest a clickable button really.

**Comment by Timecraft** [comment]
>  I'd suggest a clickable button really.

![image](https://user-images.githubusercontent.com/28582777/75484584-11a18600-5977-11ea-8f8c-d64e6ed21336.png)

**Comment by Exalm** [comment]
Another thing is that in Games we use the same view for testing gamepad by highlighing a key when you press it if you're not in mapping mode. That could be handy here as well.

**Comment by Timecraft** [comment]
Yeah, that's something I'd like to do as well
